#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

############################################################################
# Git
############################################################################
if ! hash git 2>/dev/null; then
	echo "You should install git first."
	exit 1
fi

# Set user and email
IFS= read -r -p "What name should be used for git? " GIT_NAME
git config --global user.name "$GIT_NAME"
IFS= read -r -p "What email should be used for git? " GIT_EMAIL
git config --global user.email "$GIT_EMAIL"

# Remote branch matches current by default
git config --global push.default current

# Rebase on pull
git config --global pull.rebase true

############################################################################
# ZSH
############################################################################
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	git clone https://github.com/robbyrussell/oh-my-zsh.git "$HOME/.oh-my-zsh"
fi
ln -fs "$DIR/zsh/zshrc.symlink" "$HOME/.zshrc"


############################################################################
# A splash of color!
############################################################################
COLOR_DIR="$HOME/.colors"
if [ ! -d "$COLOR_DIR" ]; then
	git clone https://github.com/bcelenza/syntax-highlighting.git "$COLOR_DIR"
fi
TERMINAL_SCHEMES="$COLOR_DIR/atelier-schemes/output/gnome-terminal"
for scheme in $(ls $TERMINAL_SCHEMES); do
	bash $TERMINAL_SCHEMES/$scheme
done

############################################################################
# Vim
############################################################################
mkdir -p "$HOME/.vim"

# Vundle
if [ ! -d "$HOME/.vim/bundle" ]; then
	mkdir -p "$HOME/.vim/bundle"
	git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
fi

ln -fs "$DIR/vim/vimrc.symlink" "$HOME/.vimrc"
vim +PluginInstall +qall
